// Mocks generated by Mockito 5.4.2 from annotations
// in siakad_sma_al_fusha/test/features/nilai/domain/usecases/get_nilai_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:siakad_sma_al_fusha/core/error/failures.dart' as _i5;
import 'package:siakad_sma_al_fusha/features/student/score_student/domain/entities/nilai.dart'
    as _i6;
import 'package:siakad_sma_al_fusha/features/student/score_student/domain/repositories/nilai_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NilaiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNilaiRepository extends _i1.Mock implements _i2.NilaiRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Nilai>>? getNilai(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNilai,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.Nilai>>?);
}
