// Mocks generated by Mockito 5.4.2 from annotations
// in siakad_sma_al_fusha/test/features/login/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:siakad_sma_al_fusha/core/platform/network_info.dart' as _i6;
import 'package:siakad_sma_al_fusha/features/login/data/datasources/login_local_data_source.dart'
    as _i5;
import 'package:siakad_sma_al_fusha/features/login/data/datasources/login_remote_datasource.dart'
    as _i3;
import 'package:siakad_sma_al_fusha/features/login/data/models/login_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginModel_0 extends _i1.SmartFake implements _i2.LoginModel {
  _FakeLoginModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRemoteDataSource extends _i1.Mock
    implements _i3.LoginRemoteDataSource {
  @override
  _i4.Future<_i2.LoginModel> postLogin({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postLogin,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.LoginModel>.value(_FakeLoginModel_0(
          this,
          Invocation.method(
            #postLogin,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.LoginModel>.value(_FakeLoginModel_0(
          this,
          Invocation.method(
            #postLogin,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.LoginModel>);
}

/// A class which mocks [LoginLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginLocalDataSource extends _i1.Mock
    implements _i5.LoginLocalDataSource {
  @override
  _i4.Future<void>? cachedLoginData(_i2.LoginModel? login) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachedLoginData,
          [login],
        ),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>?);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
